name: CI

on:
  push:
    branches:
    - mkdocs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: build docs to HTML
      env:
        CUSTOM_DOMAIN: china-speed.org
      run: | 
        apt-get update
        apt-get install -y mkdocs
        ./build-docs.sh
        echo ${{ CUSTOM_DOMAIN }} > site/CNAME
        ls -l ./site
        
    - name: deploy to gh-pages
      run: |
        npm install -g --silent gh-pages
        gh-pages --message "[skip ci] Updates" --dist site
